---
abstract: 'quoted strings with arbitrary code interpolation'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.56
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Quote-Code
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  XSLoader: 0
  perl: 5.014000
  strict: 0
  warnings: 0
version: 0.02
